import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../features/planner/services/planner_repository.dart';
import '../integrations/device_notification_service.dart';

/// Type of proactive suggestion generated by VAJRA.
enum ProactiveSuggestionType {
  upcomingEvent,
  overdueTask,
  studyReminder,
  morningBriefing,
}

/// A proactive alert or briefing item.
class ProactiveAlert {
  final String id;
  final ProactiveSuggestionType type;
  final String title;
  final String message;
  final DateTime timestamp;
  final int priority; // 1 (lowest) to 5 (urgent)

  const ProactiveAlert({
    required this.id,
    required this.type,
    required this.title,
    required this.message,
    required this.timestamp,
    this.priority = 3,
  });
}

/// ProactiveAssistant scans planner tasks and calendar events to provide timely,
/// non-intrusive reminders and briefings respecting user quiet hours.
class ProactiveAssistant {
  final PlannerRepository _plannerRepository;
  final DeviceNotificationService _notificationService;

  // Quiet hours defaults: 22:00 (10 PM) to 07:00 (7 AM)
  int quietHoursStart = 22;
  int quietHoursEnd = 7;
  DateTime? _lastProactiveNotificationTime;
  final Duration throttleDuration = const Duration(minutes: 30);

  ProactiveAssistant({
    required PlannerRepository plannerRepository,
    required DeviceNotificationService notificationService,
  })  : _plannerRepository = plannerRepository,
        _notificationService = notificationService;

  /// Checks if current time falls within configured quiet hours.
  bool isQuietHours([DateTime? time]) {
    final now = time ?? DateTime.now();
    final hour = now.hour;
    if (quietHoursStart > quietHoursEnd) {
      return hour >= quietHoursStart || hour < quietHoursEnd;
    } else {
      return hour >= quietHoursStart && hour < quietHoursEnd;
    }
  }

  /// Evaluates pending tasks and upcoming calendar events to generate proactive alerts.
  Future<List<ProactiveAlert>> generateAlerts([DateTime? referenceTime]) async {
    final now = referenceTime ?? DateTime.now();
    final List<ProactiveAlert> alerts = [];

    try {
      // 1. Check tasks for today
      final taskRes = await _plannerRepository.getTasks(now);
      if (taskRes.isSuccess && taskRes.data != null) {
        final pending = taskRes.data!.where((t) => !t.isCompleted).toList();
        for (final task in pending) {
          if (task.startTime.isBefore(now)) {
            alerts.add(ProactiveAlert(
              id: 'overdue_${task.id}',
              type: ProactiveSuggestionType.overdueTask,
              title: 'Task Overdue: ${task.title}',
              message: 'This task was scheduled earlier today. Would you like to reschedule or complete it?',
              timestamp: now,
              priority: 3,
            ));
          }
        }
      }

      // 2. Check calendar events starting in next 30 minutes
      final startWindow = now;
      final endWindow = now.add(const Duration(minutes: 30));
      final eventsRes = await _plannerRepository.getCalendarEvents(
        startDate: startWindow,
        endDate: endWindow,
      );

      if (eventsRes.isSuccess && eventsRes.data != null) {
        for (final event in eventsRes.data!) {
          final diff = event.startTime.difference(now).inMinutes;
          if (diff >= 0 && diff <= 30) {
            alerts.add(ProactiveAlert(
              id: 'event_${event.id}',
              type: ProactiveSuggestionType.upcomingEvent,
              title: 'Upcoming: ${event.title}',
              message: diff == 0 ? 'Starting now!' : 'Starting in $diff minutes.',
              timestamp: now,
              priority: 4,
            ));
          }
        }
      }
    } catch (e) {
      debugPrint('[ProactiveAssistant] generateAlerts error: $e');
    }

    return alerts;
  }

  /// Triggers a proactive notification if not in quiet hours and not throttled.
  Future<bool> dispatchProactiveNotification(ProactiveAlert alert) async {
    final now = DateTime.now();

    // Respect quiet hours unless urgent
    if (isQuietHours(now) && alert.priority < 5) {
      debugPrint('[ProactiveAssistant] Suppressing alert due to quiet hours: ${alert.title}');
      return false;
    }

    // Throttle frequency
    if (_lastProactiveNotificationTime != null &&
        now.difference(_lastProactiveNotificationTime!) < throttleDuration &&
        alert.priority < 5) {
      debugPrint('[ProactiveAssistant] Throttling proactive notification: ${alert.title}');
      return false;
    }

    try {
      final notifId = alert.id.hashCode & 0x7FFFFFFF;
      await _notificationService.showReminder(
        id: notifId,
        title: alert.title,
        body: alert.message,
      );
      _lastProactiveNotificationTime = now;
      return true;
    } catch (e) {
      debugPrint('[ProactiveAssistant] dispatchProactiveNotification error: $e');
      return false;
    }
  }
}

/// Provider for ProactiveAssistant.
final proactiveAssistantProvider = Provider<ProactiveAssistant>((ref) {
  return ProactiveAssistant(
    plannerRepository: ref.watch(plannerRepositoryProvider),
    notificationService: ref.watch(deviceNotificationServiceProvider),
  );
});
